vim.keymap.set('n', '<C-b>n', ':bnext<CR>', { desc = "Move to next buffer" })
vim.keymap.set('n', '<C-b><C-n>', ':bnext<CR>', { desc = "Move to next buffer" })
vim.keymap.set('n', '<C-b>p', ':bprev<CR>', { desc = "Move to previous buffer" })
vim.keymap.set('n', '<C-b><C-p>', ':bprev<CR>', { desc = "Move to previous buffer" })
vim.keymap.set('n', '<C-b>d', ':bd<CR>', { desc = "Delete current buffer" })
vim.keymap.set('n', '<C-b><C-d>', ':bd<CR>', { desc = "Delete current buffer" })

vim.keymap.set('n', '<C-w><C-c>', ':close<CR>', {})
vim.keymap.set('n', '<C-w>v', ':vnew<CR>', {})
vim.keymap.set('n', '<C-w><C-v>', ':vnew<CR>', {})

vim.keymap.set('n', 'grd', vim.lsp.buf.definition, {})
vim.keymap.set("n", "grf", function()
    vim.lsp.buf.format { async = true }
end, { desc = "Format current buffer" })
vim.keymap.set('n', 'grhc', function()
    vim.diagnostic.open_float(nil, { focusable = false, scope = "cursor", border = 'rounded' })
end)
vim.keymap.set('n', 'grhl', function()
    vim.diagnostic.open_float(nil, { focusable = false, scope = "line", border = 'rounded' })
end)
vim.keymap.set('n', 'grhb', function()
    vim.diagnostic.open_float(nil, { focusable = false, scope = "buffer", border = 'rounded' })
end)
vim.keymap.set('i', '<C-s>', function()
    vim.lsp.buf.signature_help({ scope = "buffer", border = 'rounded' })
end)

vim.keymap.set('n', 'K', function()
    vim.lsp.buf.hover({
        border = 'rounded',
        focusable = true,
    })
end)
vim.keymap.set('n', 'QQ', function()
    vim.cmd('qa!')
end)

vim.keymap.set('n', '<leader>!', function()
    local last_cmd = vim.fn.getreg(':')
    if last_cmd ~= '' then
        vim.api.nvim_feedkeys(":" .. last_cmd .. "!\n", 'n', false)
    else
        vim.notify("no previous Ex command", vim.log.levels.INFO, {})
    end
end, { desc = "Repeat last Ex command with ! (force) behavior" })
vim.keymap.set('n', '<leader>e', function()
    if vim.bo.filetype == 'netrw' then
        vim.cmd('bd')
    else
        vim.cmd('Explore')
    end
end, { desc = "Toggle netrw (:Ex)" })
vim.keymap.set('n', '<leader>c', function()
    vim.o.cursorline = not vim.o.cursorline
    vim.notify("cursorline " .. (vim.o.cursorline and "on" or "off"), vim.log.levels.INFO, {})
end, { desc = "Toggle cursorline" })
vim.keymap.set('n', '<leader>s', ':up<CR>', { desc = "Write buffer (if modified)" })
vim.keymap.set({ 'n', 'x' }, '<leader>y', '"+y', { desc = "Yank to system clipboard with \"+y" })
vim.keymap.set('n', '<leader>Y', '"+Y', { desc = "Yank to system clipboard with \"+Y" })
vim.keymap.set({ 'n', 'x' }, '<leader>p', '"+p', { desc = "Paste from system clipboard with \"+p" })
vim.keymap.set('n', '<leader>P', '"+P', { desc = "Paste from system clipboard with \"+P" })
vim.keymap.set('n', '<leader>/', ':nohlsearch<CR>')
local ultrasight = require('ultrasight')
vim.keymap.set('n', '<leader>us', function()
    ultrasight.toggle()
end, { noremap = true })
vim.keymap.set('n', '<leader>ul', function()
    ultrasight.listen()
end, { noremap = true })
vim.keymap.set('n', '<leader>l', function()
    vim.cmd('ls')
end, { noremap = true })
vim.keymap.set('n', '<leader>m', function()
    vim.cmd('messages')
end, { noremap = true })
vim.keymap.set('n', '<leader>n', function()
    vim.o.nu = not vim.o.nu
    vim.notify("line numbers " .. (vim.o.nu and "on" or "off"), vim.log.levels.INFO, {})
end, { desc = "Toggle cursorline" })
--vim.keymap.set('i', '<C-b>', '<Left>', { desc = "Move left" })
--vim.keymap.set('i', '<C-f>', '<Right>', { desc = "Move right" })
--vim.keymap.set('i', '<C-p>', '<Up>', { desc = "Move up" })
--vim.keymap.set('i', '<C-n>', '<Down>', { desc = "Move down" })
--vim.keymap.set('i', '<M-f>', '<C-o>w', { desc = "Move forward by word" })
--vim.keymap.set('i', '<M-b>', '<C-o>b', { desc = "Move backward by word" })
--vim.keymap.set('i', '<C-u>', '<C-o>u', { desc = "Undo" })
--vim.keymap.set('i', '<C-a>', '<C-o>0', { desc = "Move to beginning of line" })
--vim.keymap.set('i', '<C-e>', '<C-o>$', { desc = "Move to end of line" })
--vim.keymap.set('i', '<C-d>', '<Del>', { desc = "Delete character forward" })
--vim.keymap.set('i', '<M-d>', '<C-o>de', { desc = "Delete to end of word" })
--vim.keymap.set('i', '<C-k>', '<C-o>D', { desc = "Kill to end of line" })
--vim.keymap.set('i', '<C-l>', '<C-o>zz', { desc = "Center screen" })
--vim.keymap.set('i', '<C-v>', '<C-o><C-d>', { desc = "Scroll up" })
--vim.keymap.set('i', '<M-v>', '<C-o><C-u>', { desc = "Scroll down" })
